In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

train_test_split

In [6]:
shuffle_indexs = np.random.permutation(len(X))

In [7]:
shuffle_indexs

array([ 91,  10, 111,   7,   0,  37,  97,  66,  55, 133, 127,  39,  43,
        45,  86,  29,  16,  54, 124,  64,  23, 106, 145,  59,  81,  61,
       139,  31,  83,  72,  25,  38,  84,  24,  18,  41,   5, 147,  42,
       132,  57,  95, 137,  19, 115, 135,  98,  65,  32, 105,  40,  46,
       134, 110,  48,  78,  20,  12, 140,  21, 112,  99,  94,  50,  80,
        82,  17, 144,  89,  11, 128, 141,   1,  70,  63,  27, 103,   3,
       146, 125,  87, 108,  79,  88, 121, 104,  77,  90, 102, 114, 130,
       138, 118, 149,  62, 113,  92, 131,  14,  33,  34, 136, 117,  44,
       129,  51,  71, 109, 107, 143,  73,   6,  69, 126,  58,   8,  47,
       116,  56, 100,  96,  85,  49,  22,   4,  76,  53, 120, 122,  52,
        93,  67,  35, 101,  36,   9,  13,  75, 148,   2,  68,  30,  15,
       119, 123,  28,  60,  74,  26, 142])

In [8]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [9]:
test_size

30

In [13]:
test_indexs = shuffle_indexs[:test_size]
train_indexs = shuffle_indexs[test_size:]

In [14]:
# 获取训练集和测试集
X_train = X[train_indexs]
y_train = y[train_indexs]

X_test = X[test_indexs]
y_test = y[test_indexs]

In [15]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [16]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


sklearn中的train_test_split

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [67]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [68]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [69]:
from sklearn.neighbors import KNeighborsClassifier

In [70]:
knn_clf = KNeighborsClassifier(n_neighbors=5)

In [71]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [72]:
y_predict = knn_clf.predict(X_test)

In [73]:
y_predict

array([1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [74]:
y_predict == y_test

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [75]:
sum(y_predict == y_test)/len(y_test)

0.9666666666666667