# 调试梯度

In [11]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:
np.random.seed(666)
X = np.random.random(size=(1000,10))

In [13]:
true_theta = np.arange(1, 12, dtype=float)

In [14]:
X_b = np.hstack([np.ones((len(X), 1)), X])
y = X_b.dot(true_theta) + np.random.normal(size=1000)
y

array([27.11965227, 20.31927562, 32.41193706, 32.22150339, 36.88912639,
       37.18421525, 26.1623806 , 41.26780235, 26.32369961, 31.77061548,
       42.03401145, 35.40672464, 20.1417448 , 33.12847834, 46.46451582,
       24.63396208, 40.06702643, 44.7124404 , 24.85445448, 26.74072638,
       43.6846613 , 45.944478  , 39.26922226, 30.22720786, 33.96868576,
       37.26634774, 34.75283754, 40.33950708, 31.2458447 , 41.70489143,
       27.76252326, 43.41651181, 28.60873637, 33.39290766, 25.31972067,
       20.54625195, 23.77481011, 37.54691195, 36.74175339, 37.87179295,
       37.44730436, 26.44029222, 22.07450915, 46.82800306, 43.15611227,
       36.97902863, 30.90995363, 22.8410121 , 32.44582841, 46.49321909,
       23.15812527, 23.11768857, 33.66512917, 27.82206407, 39.29379967,
       28.29095104, 35.01378675, 28.73143543, 29.77693903, 37.84769401,
       31.351742  , 34.52661778, 37.46405993, 22.72362736, 18.702564  ,
       24.83241954, 31.21027275, 40.20371497, 43.59784168, 27.83

In [15]:
X.shape

(1000, 10)

In [16]:
y.shape

(1000,)

In [17]:
true_theta

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [18]:
def J(theta, X_b, y):
    try:
        return np.sum((y - X_b.dot(theta)) ** 2) / len(X_b)
    except:
        return float("inf")

In [19]:
def dJ_math(theta, X_b, y):
    return X_b.T.dot(X_b.dot(theta) - y) * 2. / len(y)

In [22]:
def dJ_debug(theta, X_b, y, epsilon=0.01):
    res = np.empty(len(theta))
    for i in range(len(theta)):
        theta_1 = theta.copy()
        theta_1[i] += epsilon
        theta_2 = theta.copy()
        theta_2[i] -= epsilon
        res[i] = (J(theta_1, X_b, y) - J(theta_2, X_b, y)) / (2 * epsilon)
    return res

In [23]:
def gradient_descent(dJ, X_b, y, initial_theta, eta, n_iters=1e4, epsilon=1e-8):
    theta = initial_theta
    i_iter = 0
    while i_iter < n_iters:
        gradient = dJ(theta, X_b, y)
        last_theta = theta
        theta = theta - gradient * eta
        if abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon:
            break
            i_iter += 1
    return theta

In [24]:
X_b = np.hstack([np.ones((len(X), 1)), X])
initial_theta = np.zeros(X_b.shape[1])
eta = 0.01

%time theta = gradient_descent(dJ_debug, X_b, y, initial_theta, eta)

Wall time: 8.39 s


In [25]:
theta

array([ 1.07964823,  2.05912453,  2.92524399,  4.12967602,  5.05886967,
        5.91270186,  6.98378845,  8.0081538 ,  8.87263904,  9.99409247,
       10.91497018])

In [26]:
X_b = np.hstack([np.ones((len(X), 1)), X])
initial_theta = np.zeros(X_b.shape[1])
eta = 0.01

%time theta = gradient_descent(dJ_math, X_b, y, initial_theta, eta)
theta

Wall time: 1.35 s


array([ 1.07964823,  2.05912453,  2.92524399,  4.12967602,  5.05886967,
        5.91270186,  6.98378845,  8.0081538 ,  8.87263904,  9.99409247,
       10.91497018])